language: python
python:
  - "3.5"

sudo: required

services:
  - docker

before_install:
  - sudo service docker stop

install:
  - pip install -r dev_requirements.txt
  - pip install .

script:
  - sudo nose2
