sudo: required
dist: trusty

language: python

python:
  - "3.5"

services:
  - docker

before_install:
  - sudo adduser ${USER} root
  - sudo adduser ${USER} docker

install:
  - export VENV=.venv
  - make install

script:
  - export VENV=.venv
  - export TEST_DOCKER_HOST=tcp://127.0.0.1:23750
  - export TEST_DOCKER_TLS_HOST=tcp://127.0.0.1:23760
  - make test
