# Project information
site_name: 'asyncio-docker'
site_description: 'Asynchronous docker client for python'
site_author: 'Raymond Reggers'
site_url: 'https://adaptivdesign.github.io/asyncio-docker'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/adaptivdesign/asyncio-docker'

# Copyright
copyright: 'Copyright (c) 2016 Adaptiv Design'

# Theme
theme: 'material'

# Extra
extra:
  version: '1.23'
  #logo: 'images/logo.png'
  palette:
    primary: 'teal'
    accent: 'deep orange'
  author:
    github: 'adaptivdesign'


markdown_extensions:
    - admonition
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - codehilite(css_class=code)


# Pages
pages:
  - About: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
